openapi: 3.0
info:
  title: requestBody bug repro
paths:
  /foo:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bar:
                  type: integer
